name: Docker Image CI

on:
  push:
    tags:
      - "v*.*.*" # switched to pushes on tags instead of main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo  
        uses: actions/checkout@v4

      - name: Docker Meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/ivery-ceg3120
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          # tags: insanityveins/ivery-ceg3120:latest old working
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.output.labels }}